[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-accounts-cluster-bench"
version = "1.10.35"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = false

[dependencies]
clap = "2.33.1"
log = "0.4.14"
rand = "0.7.0"
<<<<<<< HEAD
rayon = "1.5.1"
solana-account-decoder = { path = "../account-decoder", version = "=1.10.35" }
solana-clap-utils = { path = "../clap-utils", version = "=1.10.35" }
solana-client = { path = "../client", version = "=1.10.35" }
solana-faucet = { path = "../faucet", version = "=1.10.35" }
solana-gossip = { path = "../gossip", version = "=1.10.35" }
solana-logger = { path = "../logger", version = "=1.10.35" }
solana-measure = { path = "../measure", version = "=1.10.35" }
solana-net-utils = { path = "../net-utils", version = "=1.10.35" }
solana-runtime = { path = "../runtime", version = "=1.10.35" }
solana-sdk = { path = "../sdk", version = "=1.10.35" }
solana-streamer = { path = "../streamer", version = "=1.10.35" }
solana-transaction-status = { path = "../transaction-status", version = "=1.10.35" }
solana-version = { path = "../version", version = "=1.10.35" }
spl-token = { version = "=3.3.1", features = ["no-entrypoint"] }
=======
rayon = "1.5.3"
solana-account-decoder = { path = "../account-decoder", version = "=1.11.6" }
solana-clap-utils = { path = "../clap-utils", version = "=1.11.6" }
solana-client = { path = "../client", version = "=1.11.6" }
solana-faucet = { path = "../faucet", version = "=1.11.6" }
solana-gossip = { path = "../gossip", version = "=1.11.6" }
solana-logger = { path = "../logger", version = "=1.11.6" }
solana-measure = { path = "../measure", version = "=1.11.6" }
solana-net-utils = { path = "../net-utils", version = "=1.11.6" }
solana-runtime = { path = "../runtime", version = "=1.11.6" }
solana-sdk = { path = "../sdk", version = "=1.11.6" }
solana-streamer = { path = "../streamer", version = "=1.11.6" }
solana-transaction-status = { path = "../transaction-status", version = "=1.11.6" }
solana-version = { path = "../version", version = "=1.11.6" }
spl-token = { version = "=3.5.0", features = ["no-entrypoint"] }
>>>>>>> b725b8617 (spl: Bump token to 3.5.0 and ata to 1.1.0 (#26921))

[dev-dependencies]
solana-core = { path = "../core", version = "=1.10.35" }
solana-local-cluster = { path = "../local-cluster", version = "=1.10.35" }
solana-test-validator = { path = "../test-validator", version = "=1.10.35" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
